import { learningModuleSchema } from "./schema";
import { knowledgeModules } from "./knowledge";

const reviewedOn = "2026-07-10";
const frameworkReference = {
  label: "ERAC Essential Performance Capabilities for Electricians",
  sourceType: "framework" as const,
  edition: "2024",
  reference: "Capability mapping only",
  url: "https://www.erac.gov.au/licensing/essential-performance-capabilities-for-electricians/",
  reviewedOn,
};

const moduleOutlines = [
  { id: "safety-electrical-risk", title: "Safety and electrical risk", summary: "Build a repeatable approach to workplace risk, safe work planning and electrical emergency awareness.", domain: "safety", level: "capstone", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 1–4", estimatedMinutes: 42, progress: 88, objectives: ["Explain how risk controls are selected", "Recognise when work must stop and be escalated"], commonErrors: ["Treating PPE as the first and only control"], relatedModules: ["isolation-testing-faults"], references: [frameworkReference] },
  { id: "electrical-fundamentals", title: "Electrical fundamentals", summary: "Connect DC and AC relationships to measurements, calculations and practical circuit behaviour.", domain: "fundamentals", level: "foundation", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 5–10", estimatedMinutes: 65, progress: 76, objectives: ["Apply electrical relationships with correct units", "Explain phase and power relationships"], commonErrors: ["Substituting line and phase values without checking the connection"], relatedModules: ["energy-systems", "motors-transformers"], references: [frameworkReference] },
  { id: "wiring-rules-design", title: "Wiring rules and design", summary: "Practise the decisions that connect installation purpose, circuit arrangement, demand and cable selection.", domain: "design", level: "capstone", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 11–15", estimatedMinutes: 78, progress: 61, objectives: ["Describe the installation design decision sequence", "Recognise the inputs needed for cable selection"], commonErrors: ["Selecting a conductor from load current alone"], relatedModules: ["conductors-circuits", "switchgear-control"], references: [frameworkReference] },
  { id: "energy-systems", title: "Energy systems", summary: "Review electromagnetism, three-phase systems, power factor, renewable generation, storage and alternate supplies.", domain: "energy", level: "intermediate", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 16–20", estimatedMinutes: 64, progress: 52, objectives: ["Explain balanced three-phase relationships", "Identify alternate and stored-energy sources"], commonErrors: ["Assuming the grid main switch removes every source"], relatedModules: ["electrical-fundamentals", "isolation-testing-faults"], references: [frameworkReference] },
  { id: "conductors-circuits", title: "Conductors and circuits", summary: "Organise conductor construction, installation influences, wiring systems and protection coordination.", domain: "conductors", level: "intermediate", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 21–23", estimatedMinutes: 46, progress: 69, objectives: ["Identify installation influences that affect selection", "Connect conductor performance to protective devices"], commonErrors: ["Ignoring grouping, temperature or mechanical influences"], relatedModules: ["wiring-rules-design", "switchgear-control"], references: [frameworkReference] },
  { id: "switchgear-control", title: "Switchgear and control gear", summary: "Compare control, isolation and protection functions without treating unlike devices as interchangeable.", domain: "protection", level: "capstone", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 24–27", estimatedMinutes: 55, progress: 64, objectives: ["Distinguish switching, isolation and protection roles", "Explain why protective-device coordination matters"], commonErrors: ["Assuming an RCD provides every form of circuit protection"], relatedModules: ["wiring-rules-design", "isolation-testing-faults"], references: [frameworkReference] },
  { id: "accessories-equipment", title: "Accessories and equipment", summary: "Apply suitability, environmental influence and safe installation thinking to common electrical equipment.", domain: "equipment", level: "intermediate", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: false, capabilityRange: "EPC 28–31", estimatedMinutes: 44, progress: 81, objectives: ["Relate equipment selection to its environment", "Recognise installation and maintenance constraints"], commonErrors: ["Treating an IP rating as sufficient without considering installation details"], relatedModules: ["specialist-areas"], references: [frameworkReference] },
  { id: "earthing-men", title: "Earthing, bonding and MEN", summary: "Trace fault-current paths and connect earthing arrangements to automatic disconnection and verification.", domain: "earthing", level: "capstone", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 32–33", estimatedMinutes: 58, progress: 58, objectives: ["Explain the purpose of protective earthing", "Trace a conceptual MEN fault-current path"], commonErrors: ["Confusing neutral continuity with protective-earthing continuity"], relatedModules: ["switchgear-control", "isolation-testing-faults"], references: [frameworkReference] },
  { id: "motors-transformers", title: "Motors and transformers", summary: "Review operating principles, starting, control, protection, common symptoms and safe diagnostic planning.", domain: "machines", level: "intermediate", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 34–38", estimatedMinutes: 72, progress: 74, objectives: ["Relate motor symptoms to plausible fault groups", "Apply transformer ratio relationships"], commonErrors: ["Testing before identifying every source and stored-energy hazard"], relatedModules: ["electrical-fundamentals", "isolation-testing-faults"], references: [frameworkReference] },
  { id: "isolation-testing-faults", title: "Isolation, testing and faults", summary: "Rehearse safe isolation, verification planning, result interpretation, fault diagnosis and commissioning logic.", domain: "verification", level: "capstone", jurisdiction: "AU", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 39–42", estimatedMinutes: 86, progress: 42, objectives: ["Describe a controlled isolation process", "Choose a logical verification or diagnostic next step"], commonErrors: ["Treating opening a local switch as effective isolation"], relatedModules: ["safety-electrical-risk", "earthing-men", "energy-systems"], references: [frameworkReference] },
  { id: "specialist-areas", title: "Specialist areas and HV awareness", summary: "Recognise specialist boundaries, wet and hazardous locations, construction contexts and high-voltage risks.", domain: "specialist", level: "capstone", jurisdiction: "state-specific", sourceStatus: "original-summary", contentStatus: "outline", safetyCritical: true, capabilityRange: "EPC 43–48", estimatedMinutes: 68, progress: 47, objectives: ["Identify when specialist competency is required", "Recognise conditions that change equipment or work requirements"], commonErrors: ["Applying general installation assumptions to a specialist location"], relatedModules: ["accessories-equipment", "safety-electrical-risk"], references: [frameworkReference] },
];

export const modules = learningModuleSchema.array().parse(moduleOutlines.map((module) => ({
  ...module,
  ...(knowledgeModules[module.id] ?? {}),
})));

export const moduleById = new Map(modules.map((module) => [module.id, module]));
