import { practiceQuestionSchema } from "./schema";

export const questions = practiceQuestionSchema.array().parse([
  { id: "effective-isolation", moduleId: "isolation-testing-faults", prompt: "Which description best represents effective isolation before working on a final subcircuit?", options: ["Open the nearest wall switch", "Identify all sources, isolate, secure and prove de-energised with verified equipment", "Remove only the active conductor", "Rely on another worker's confirmation"], answerIndex: 1, explanation: "Effective isolation is a controlled process that identifies all possible sources and confirms the relevant conductors are de-energised using suitable, verified test equipment.", misconception: "A local switch is sufficient isolation", safetyCritical: true, contentStatus: "draft-unverified" },
  { id: "deenergised-first", moduleId: "isolation-testing-faults", prompt: "Why are appropriate de-energised checks normally completed before energised verification?", options: ["They reduce electricity cost", "They establish safety and connection integrity before voltage is introduced", "They replace visual inspection", "They only apply to three-phase work"], answerIndex: 1, explanation: "Inspection and de-energised checks can establish important aspects of continuity, insulation, polarity and connection integrity before energisation introduces additional risk.", misconception: "Energised testing is always the fastest first step", safetyCritical: true, contentStatus: "draft-unverified" },
  { id: "three-phase-power", moduleId: "electrical-fundamentals", prompt: "Which expression represents real power in a balanced three-phase load?", options: ["P = V × I", "P = √3 × VL × IL × cos φ", "P = I² ÷ R", "P = VL ÷ IL"], answerIndex: 1, explanation: "For a balanced three-phase load, real power uses line voltage, line current, the square root of three and power factor.", misconception: "Single-phase power relationships transfer unchanged", safetyCritical: false, contentStatus: "draft-unverified" },
  { id: "men-purpose", moduleId: "earthing-men", prompt: "What is the safety purpose of the MEN connection in a typical Australian low-voltage installation?", options: ["Limit normal load current", "Support a low-impedance fault path so protection can operate", "Replace the main switch", "Prevent every possible shock without other measures"], answerIndex: 1, explanation: "The MEN arrangement supports the fault-current path used for automatic disconnection. It does not replace correct protection, bonding, design or verification.", misconception: "MEN alone provides complete protection", safetyCritical: true, contentStatus: "draft-unverified" },
  { id: "motor-start", moduleId: "motors-transformers", prompt: "A capacitor-start single-phase motor hums but does not accelerate. Which area is a plausible first investigation?", options: ["Starting circuit, capacitor or switching mechanism", "Lighting circuit polarity", "Only the premises earth electrode", "Supply-transformer power-factor correction"], answerIndex: 0, explanation: "A starting-circuit problem can leave the motor without adequate starting torque. A safe, systematic diagnostic plan is required before testing components.", misconception: "A humming motor always has a mechanical load fault", safetyCritical: false, contentStatus: "draft-unverified" },
  { id: "rcd-role", moduleId: "switchgear-control", prompt: "Which statement best describes the role of an RCD?", options: ["It provides every form of overload protection", "It detects residual-current imbalance and can disconnect", "It makes live work safe", "It removes the need for protective earthing"], answerIndex: 1, explanation: "An RCD detects residual-current imbalance. Its presence does not authorise live work or replace earthing and overcurrent-protection requirements.", misconception: "An RCD is a complete protection system", safetyCritical: true, contentStatus: "draft-unverified" },
  { id: "transformer-ratio", moduleId: "motors-transformers", prompt: "An ideal transformer has 1000 primary turns and 100 secondary turns. With 230 V on the primary, what is the approximate secondary voltage?", options: ["2.3 V", "23 V", "230 V", "2300 V"], answerIndex: 1, explanation: "The secondary-to-primary turns ratio is 0.1, so the ideal secondary voltage is 230 V multiplied by 0.1.", misconception: "Turns ratio is inverted", safetyCritical: false, contentStatus: "draft-unverified" },
  { id: "alternate-supplies", moduleId: "energy-systems", prompt: "Why must isolation planning consider PV, batteries and generators?", options: ["They may remain alternate or stored sources after the grid main switch opens", "They always operate at extra-low voltage", "They remove lock-out needs", "An RCD mechanically isolates them"], answerIndex: 0, explanation: "One switch may not remove every source. Alternate supplies, stored energy and automatic starting must be identified and controlled in the work plan.", misconception: "The grid main switch removes all energy", safetyCritical: true, contentStatus: "draft-unverified" },
]);
